# Generated by Django 4.2.5 on 2023-09-25 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message",
            new_name="CustomMessage",
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterModelTable(
            name="custommessage",
            table="custom_message",
        ),
    ]
